# Generated by Django 3.0 on 2022-09-12 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='letting',
            options={'verbose_name': 'Letting', 'verbose_name_plural': 'Lettings'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelTable(
            name='address',
            table='lettings_address',
        ),
        migrations.AlterModelTable(
            name='letting',
            table='lettings_letting',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profiles_profile',
        ),
    ]
