# Generated by Django 3.0 on 2022-09-12 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0003_auto_20220912_2318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
